SOURCE_DIR="/d/cloud"
BACKUP_DIR="/d/backup"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
BACKUP_FILE="backup_$TIMESTAMP.tar.gz"
#CREATE DIR IF NOT EXISTS
mkdir -p "$BACKUP_DIR"
#CREATE COMPRESSED BACKUP OF THE SOURCE DIR
tar -czf "$BACKUP_DIR/$BACKUP_FILE" "$SOURCE_DIR"